python3 train.py \
                --model RF \
                --aggregation 50pt \
                --target BuildingFootprint \
                --training_dataset /data/lyy/BuildingProject/dataset/patch_data_50pt_s15_100m_train.h5  \
                --test_dataset /data/lyy/BuildingProject/dataset/patch_data_50pt_s15_100m_test.h5 \
                --reduction_ratio 0.5 \
                --num_cpu 24 \
                --num_cv 1 \
                --train_with_evaluation True \
                --selected False \
                --chunk_size 20000 \
                --saved True \
                --save_suffix _s15_100m
